package com.example.FreshFood.enums;

public enum Permission {
    PRODUCT_VIEW,
    PRODUCT_SEARCH,
    PRODUCT_FILTER,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    PRODUCT_IMAGE_UPLOAD,
    PRODUCT_APPROVE,

    FAVORITE_CREATE,
    FAVORITE_DELETE,
    FAVORITE_VIEW,

    CART_VIEW,
    CART_CREATE,
    CART_UPDATE,
    CART_DELETE,

    ORDER_CREATE,
    ORDER_VIEW_OWN,
    ORDER_VIEW_FARMER,
    ORDER_VIEW_ALL,
    ORDER_UPDATE,

    USER_VIEW,
    USER_LOCK,
    USER_UNLOCK,

    REVENUE_VIEW_OWN,
    REVENUE_VIEW_ALL,

    DASHBOARD_VIEW
}
